// namemap.js — auto-generated from GD_Names.xlsx
// Provides Japanese translations for room names.

// Normalise a raw room name to a lookup key:
//   lowercase, spaces/commas/slashes → underscore, collapse repeats
export function normaliseKey(name) {
  return name
    .toLowerCase()
    .replace(/[\s,/\-]+/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_|_$/g, '');
}

export function getJapaneseName(rawName) {
  if (!rawName) return null;
  const key = normaliseKey(rawName);

  // 1. Exact match
  if (NAME_MAP[key]) return NAME_MAP[key];

  // 2. Strip trailing _<digits>  e.g. light_garden_1 -> light_garden
  const noNum = key.replace(/_\d+$/, '');
  if (noNum !== key && NAME_MAP[noNum]) return NAME_MAP[noNum];

  // 3. Strip trailing _<single-or-multi letter suffix>  e.g. conference_room_a
  const noSuffix = key.replace(/_[a-z]+$/, '');
  if (noSuffix !== key && NAME_MAP[noSuffix]) return NAME_MAP[noSuffix];

  // 4. Strip both number AND letter suffix  e.g. "consultation_room_a_2"
  const noNumSuffix = noSuffix.replace(/_\d+$/, '');
  if (noNumSuffix !== noSuffix && NAME_MAP[noNumSuffix]) return NAME_MAP[noNumSuffix];

  return null;
}

// ── Lookup table ──────────────────────────────────────────────────────────────
const NAME_MAP = {
  'account_waiting_area': '会計待合',
  'four_bed_rooms': '4床室',
  'single_bed_rooms': '1床室',
  'accounting_and_general_affairs_room': '経理・総務部室',
  'accounting_and_general_affairs_room1': '経理・総務部室',
  'accounting_and_general_affairs_room2': '経理・総務部室',
  'admin_passage': '管理者の通路',
  'angiography_room': '血管造影検査室',
  'audiology_examination_room': '聴力検査室',
  'bath': '浴室',
  'bath_bath_dressing': '浴室＋脱衣室',
  'bath_dressing': '脱衣室',
  'bmd_and_mer_room': '骨塩測定室・マンモグラフィ',
  'board_of_directors_room': '理事長室',
  'boiler_room': 'ボイラー室',
  'break_room': '休憩室',
  'catering_room': '配膳室',
  'central_supply_room': '中央材料室',
  'central_warehouse': '中央倉庫',
  'chemical_storage': 'ミキシング 薬剤庫',
  'chemotherapy_room': '化学療法室',
  'clean_linen_room': '清潔リネン庫',
  'cleaning_and_preparation_room': '洗浄・準備室',
  'common_passage': '共用廊下',
  'conference_room': 'カンファレンス室',
  'conference_room_a': '会議室',
  'conference_room_e': '会議室',
  'consultation': '診察室',
  'consultation_room': '診察室',
  'consultation_room_a': '診療室',
  'consultation_room_b': '診察室',
  'consultation_room_c': '診療室',
  'consultation_room_g': '診療室',
  'control_room': '機械室・操作室',
  'corridor': '病棟廊下',
  'ct_scan_room': 'CT撮影室',
  'deputy_directors_office': '副院長室',
  'director_of_nursing_office': '看護部長室',
  'directors_office': '院長室',
  'doctor_staff_waiting_room': '医師・スタッフ控室',
  'eeg_examination_room': '脳波検査室',
  'electrocardiogram_examination_room': '心電図検査室',
  'electromyography_examination_room': '筋電図検査室',
  'elevator': 'EV',
  'elevator_shaft': 'EV',
  'emergency_room': '救急室',
  'endoscopy_room': '内視鏡室',
  'entrance_exit_passage_for_staff': '職員用出入口通路',
  'entrance_hall': 'エントランスホール',
  'equipment_machine_room': '器材置場',
  'equipment_room': '器材庫',
  'equipment_room_a': '器材置場',
  'ev_hall': 'EVホール',
  'ev_lobby': 'EVロビー',
  'ev_shaft_-_1': 'EV',
  'ev_shaft_-_2': 'EV',
  'examination_room': '診察処置室',
  'external_stairs': '外部階段',
  'extra_room': '多目的室',
  'family_waiting_area': '家族待合ロビー',
  'fire_pump_room_and_sp_pump_room': '消化ポンプ室・SPポンプ室',
  'functional_training_room': '機能訓練室',
  'fundus_examination_room': '眼底検査室',
  'guard_room': '守衛室',
  'hcwc': 'HCWC',
  'hcwc1': 'HCWC',
  'hcwc2': 'HCWC',
  'interview_room': '面談室',
  'iv': '点滴室',
  'iv_room': '点滴室',
  'kitchen': '厨房・調理室/休憩室・栄養指導室',
  'laundry': '洗濯室',
  'laundry_and_drying_room': '洗濯乾燥室',
  'library': '図書室',
  'light_garden': '光庭',
  'light_garden-1': '光庭',
  'light_garden-2': '光庭',
  'linen_storage_room': 'リネン庫',
  'lobby': 'ロビー',
  'machine_room': '機械室',
  'main_conference_room': '大会議室',
  'me_room': 'ME機器管理室',
  'medical_department_dialysis_room': '人工透析室',
  'medical_gas_manifold_room': '医療ガスマニホールド室',
  'medical_history_room': '病歴室',
  'medical_office_on_call_private_doctors_room': '医局・医師個室・当直室',
  'medical_office_room': '医療事務室',
  'medical_record_room': '病歴室',
  'medical_waste_storage_room': '医療廃棄物保管庫',
  'meeting_room': '大会議室',
  'men\'s_locker_room': '男子更衣室',
  'men_locker': '男子更衣室',
  'mortuary_room': '霊安室',
  'mri_room': 'MRI撮影室',
  'multi_purpose_hall': '大会議室',
  'nap_room': '仮眠室',
  'nursery_room': '託児所',
  'office_managers_office': '事務部長室',
  'operating_hall_room': 'OPホール',
  'operating_large_room': '手術室',
  'operating_large_room2': '手術室',
  'operating_pre_room': 'OP前室',
  'operating_room': '手術室',
  'operating_small_room': '手術室',
  'operating_small_room2': '手術室',
  'pharmacy_area': '薬局エリア',
  'pharmacy_dispensing_room': '薬局エリア',
  'physiological_examination_corridor': '生理検査廊下',
  'psychological_examination_preparation_room': '生理検査準備室',
  'psychological_examination_waiting_room': '生理検査待合',
  'reception': '受付',
  'reception_a': '画像診断受付',
  'reception_and_waiting_area': '受付・待合',
  'reception_and_waiting_area_e': '受付・待合',
  'reception_area': '受付',
  'reception_area_c': '受付',
  'reception_b': '外来受付',
  'reception_c': 'リハビリスタッフ室',
  'reception_room': '応接室',
  'reception_room_e': '応接室',
  'se_room': 'SE室',
  'server_water_heater_room': 'サーバー・給湯室',
  'shop': '売店',
  'special_bath': '特浴',
  'special_bath_special_dressing': '特浴（機械浴室）＋脱衣室',
  'special_dressing': '脱衣室',
  'specimen_testing_room': '検体検査室',
  'speech_therapy_room': '言語治療ST室',
  'ss': 'SS',
  'staff_cafeteria': '職員食堂',
  'staff_corridor': 'スタッフ通路',
  'staff_room': 'リハビリスタッフ室',
  'stair': '階段',
  'staircase': '階段',
  'stairs': '階段',
  'stockpile_warehouse': '備蓄倉庫',
  'storage': 'リネン庫',
  'storage_b': 'ストレージ',
  'supply_department_passage': '供給部門通路',
  'system_engineer_room': 'SE室',
  'ultrasound_examination_room': '超音波検査室',
  'unclean_linen_room': '不潔リネン庫',
  'unit_dressing_1': '脱衣室',
  'unit_dressing_2': '脱衣室',
  'unit_shower_1': 'シャワーブース',
  'unit_shower_2': 'シャワーブース',
  'unit_shower_unit_dressing': 'シャワーブース＋脱衣室',
  'vertical_corridor': '通路',
  'waiting_hall': '待合ホール',
  'waiting_hall_a': '画像診断待合',
  'waiting_hall_b': '待合ホール',
  'waiting_hall_c': 'リハビリ待合',
  'waiting_hall_g': 'リハビリ待合',
  'waiting_room': '待合',
  'waste_disposal_room': '汚物処理室',
  'waste_storage_room': '廃棄物保管庫',
  'water_room': 'サーバー・給湯室',
  'wc': 'WC',
  'wc2': 'WC×2, HCWC',
  'wc_1': '男子トイレ',
  'wc_2': '女子トイレ',
  'wc_b': 'WC×2, HCWC',
  'wc_c_e': 'WC×2, HCWC',
  'wc_e': 'WC×2, HCWC',
  'wc_f': 'WC×2, HCWC',
  'wc_passage': '共用通路',
  'windbreak': '風除室',
  'women\'s_changing_room': '女子更衣室',
  'women_locker': '女子更衣室',
  'xray_room': 'X線撮影室',
  'xray_tv_examination_room': 'X線TV操作室',
};